In [1]:
import duckdb

In [2]:
con = duckdb.connect('../customer_analytics.duckdb')

In [6]:
with open("../sql/01_create_bronze_tables.sql", "r", encoding="utf-8") as file:
    con.execute(file.read())
with open("../sql/02_create_silver_tables.sql", "r", encoding="utf-8") as file:
    con.execute(file.read())
with open("../sql/03_create_gold_tables.sql", "r", encoding="utf-8") as file:
    con.execute(file.read())

In [7]:
con.execute("SHOW TABLES").df()

                                 name
0                    bronze_customers
1              gold_churn_by_contract
2      gold_churn_by_internet_service
3  gold_churn_by_monthly_charge_group
4        gold_churn_by_payment_method
5          gold_churn_by_tenure_group
6                gold_revenue_summary
7                    silver_customers

In [8]:
con.execute("SELECT * FROM gold_churn_by_contract").df()

         Contract  total_customers  churned_customers  churn_rate
0  Month-to-month             3875             1655.0       42.71
1        One year             1472              166.0       11.28
2        Two year             1685               48.0        2.85

In [9]:
gold_tables = [
    "gold_churn_by_contract",
    "gold_churn_by_payment_method",
    "gold_churn_by_tenure_group",
    "gold_churn_by_monthly_charge_group",
    "gold_revenue_summary",
    "gold_churn_by_internet_service"
]

for table in gold_tables:
    df_gold = con.execute(f"SELECT * FROM {table}").df()
    df_gold.to_csv(f"../data/processado/{table}.csv", index=False)